import os

from dotenv import load_dotenv


load_dotenv()


PLSMEME_REDDIT_CLIENT_ID = os.environ['PLSMEME_REDDIT_CLIENT_ID']
PLSMEME_REDDIT_CLIENT_SECRET = os.environ['PLSMEME_REDDIT_CLIENT_SECRET']
PLSMEME_REDDIT_USERNAME = os.environ['PLSMEME_REDDIT_USERNAME']
PLSMEME_REDDIT_PASSWORD = os.environ['PLSMEME_REDDIT_PASSWORD']
PLSMEME_REDDIT_USER_AGENT = os.environ['PLSMEME_REDDIT_USER_AGENT']
